require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Include:
    - "spec/**/*"
  Exclude:
    - "lib/**/*"
    - "bin/**/*"

Metrics/BlockLength:
  IgnoredMethods:
    - context
    - describe
