version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: active-pdf-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_HOST_PORT}:5432
    command: "postgres -c 'max_connections=500'"
  server:
    tty: true
    stdin_open: true
    build:
      context: docker
      dockerfile: Dockerfile.rails
      target: base
    depends_on:
      - postgres
    volumes:
      - .:/app:cached
    ports:
      - ${APP_HOST_PORT}:3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    command: sh ./docker/entrypoint.sh
    privileged: true

volumes:
  postgres_data: {}

networks:
  default:
    name: active_pdf_default
