version: "3"

x-defaults: &base
  tty: true
  stdin_open: true
  build:
    context: docker
    dockerfile: Dockerfile.rails
    target: base
  depends_on:
    - postgres
    - redis
  volumes:
    - .:/app:cached
    - node_modules:/node_modules
  privileged: true
  env_file:
    - ".env"

services:
  postgres:
    image: postgres:latest
    container_name: active-pdf-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_HOST_PORT}:5432
    command: "postgres -c 'max_connections=500'"
  server:
    <<: *base
    container_name: active-pdf-server
    command: sh ./docker/entrypoint.sh
    ports:
      - ${APP_HOST_PORT}:3000
  redis:
    image: redis:latest
    container_name: active-pdf-redis
    command: redis-server
    ports:
      - ${REDIS_PORT}:6379
  sidekiq:
    <<: *base
    container_name: active-pdf-sidekiq
    command: sh ./docker/entrypoint-sidekiq.sh
  vite:
    <<: *base
    container_name: active-pdf-vite
    command: sh ./docker/entrypoint-vite.sh
    ports:
      - ${APP_VITE_PORT}:3036

volumes:
  postgres_data: {}
  node_modules: {}

networks:
  default:
    name: active_pdf_default
