default: &default
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/1") %>

development:
  <<: *default
  channel_prefix: <%= ENV.fetch("REDIS_CHANNEL_PREFIX", "active_pdf_development") %>

test:
  <<: *default
  adapter: test

production:
  <<: *default
  channel_prefix: <%= ENV.fetch("REDIS_CHANNEL_PREFIX", "active_pdf_production") %>
