---
:concurrency: 5
production:
  :concurrency: 10
:queues:
  - default
  - mailers

:scheduler:
  :schedule:
    hello_world_job:
      cron: "0 * * * * *"
      class: HelloWorldJob
    hello_world_worker:
      cron: "0 * * * * *"
      class: HelloWorldWorker
