---
:concurrency: 5
production:
  :concurrency: 10
:queues:
  - default
  - mailers

:scheduler:
  :schedule:
    # hello_world:
    #   cron: '0 * * * * *'   # Runs once per minute
    #   class: HelloWorld
